version: "3.8"

services:
  web:
    restart: always
    build: .
    command: python src/manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:16.1
    container_name: db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=twitter_clone
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Resolute*2024
